Repository AY2324S1-CS2103T-W15-1/tp, pull requests merged in 2023-10, with the labels that each got.

#73 Complete add-task-userStory and morph to add-task
  docs/DeveloperGuide.md
  docs/tutorials/AddRemark.md
  docs/tutorials/TracingCode.md
  src/main/java/profplan/MainApp.java
  src/main/java/profplan/logic/Logic.java
  src/main/java/profplan/logic/commands/AddCommand.java
  src/main/java/profplan/logic/commands/ClearCommand.java
  src/main/java/profplan/logic/commands/DeleteCommand.java
  src/main/java/profplan/logic/commands/EditCommand.java
  src/main/java/profplan/logic/commands/ExitCommand.java
  src/main/java/profplan/logic/commands/FindCommand.java
  src/main/java/profplan/logic/commands/ListCommand.java
  src/main/java/profplan/logic/parser/AddCommandParser.java
  src/main/java/profplan/model/Model.java
  src/main/java/profplan/model/ModelManager.java
  src/main/java/profplan/model/ProfPlan.java
  src/main/java/profplan/model/ReadOnlyProfPlan.java
  src/main/java/profplan/model/tag/Tag.java
  src/main/java/profplan/model/task/Address.java
  src/main/java/profplan/model/task/Email.java
  src/main/java/profplan/model/task/Name.java
  src/main/java/profplan/model/task/Phone.java
  src/main/java/profplan/model/task/Task.java
  src/main/java/profplan/storage/JsonSerializableProfPlan.java
  src/test/java/profplan/logic/commands/CommandTestUtil.java
  src/test/java/profplan/logic/commands/DeleteCommandTest.java
  src/test/java/profplan/logic/commands/EditCommandTest.java
  src/test/java/profplan/logic/parser/AddCommandParserTest.java
Labels: priority.High

#77 Update Find Command
  src/main/java/profplan/logic/commands/FindCommand.java
Labels: priority.High

#78 Branch add priority
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
  src/main/java/profplan/logic/Messages.java
  src/main/java/profplan/logic/commands/AddCommand.java
  src/main/java/profplan/logic/commands/EditCommand.java
  src/main/java/profplan/logic/parser/AddCommandParser.java
  src/main/java/profplan/logic/parser/CliSyntax.java
  src/main/java/profplan/logic/parser/EditCommandParser.java
  src/main/java/profplan/logic/parser/ParserUtil.java
  src/main/java/profplan/model/task/Phone.java
  src/main/java/profplan/model/task/Priority.java
  src/main/java/profplan/model/task/Task.java
  src/main/java/profplan/model/util/SampleDataUtil.java
  src/main/java/profplan/storage/JsonAdaptedTask.java
  src/main/java/profplan/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/data/JsonProfPlanStorageTest/invalidAndValidTaskProfPlan.json
  src/test/data/JsonProfPlanStorageTest/invalidTaskProfPlan.json
  src/test/data/JsonSerializableProfPlanTest/duplicateTaskProfPlan.json
  src/test/data/JsonSerializableProfPlanTest/invalidTaskProfPlan.json
  src/test/data/JsonSerializableProfPlanTest/typicalTasksProfPlan.json
  src/test/java/profplan/logic/LogicManagerTest.java
  src/test/java/profplan/logic/commands/CommandTestUtil.java
  src/test/java/profplan/logic/commands/EditCommandTest.java
  src/test/java/profplan/logic/commands/EditTaskDescriptorTest.java
  src/test/java/profplan/logic/parser/AddCommandParserTest.java
  src/test/java/profplan/logic/parser/EditCommandParserTest.java
  src/test/java/profplan/logic/parser/ParserUtilTest.java
  src/test/java/profplan/model/task/NameContainsKeywordsPredicateTest.java
  src/test/java/profplan/model/task/PhoneTest.java
  src/test/java/profplan/model/task/PriorityTest.java
  src/test/java/profplan/model/task/TaskTest.java
  src/test/java/profplan/storage/JsonAdaptedTaskTest.java
  src/test/java/profplan/testutil/EditTaskDescriptorBuilder.java
  src/test/java/profplan/testutil/TaskBuilder.java
  src/test/java/profplan/testutil/TaskUtil.java
  src/test/java/profplan/testutil/TypicalTasks.java
Labels: priority.High

#99 Fix bug
  build.gradle
  src/main/java/profplan/logic/commands/MarkCommand.java
  src/main/java/profplan/logic/commands/UnmarkCommand.java
  src/main/java/profplan/model/task/DueDate.java
Labels: type.Bug

#121 Remove `email`, `address`
  bin/main/view/TaskListCard.fxml
  src/main/java/profplan/MainApp.java
  src/main/java/profplan/logic/Messages.java
  src/main/java/profplan/logic/commands/AddCommand.java
  src/main/java/profplan/logic/commands/DescriptionCommand.java
  src/main/java/profplan/logic/commands/EditCommand.java
  src/main/java/profplan/logic/commands/SetCommand.java
  src/main/java/profplan/logic/parser/AddCommandParser.java
  src/main/java/profplan/logic/parser/CliSyntax.java
  src/main/java/profplan/logic/parser/EditCommandParser.java
  src/main/java/profplan/logic/parser/ParserUtil.java
  src/main/java/profplan/model/task/Address.java
  src/main/java/profplan/model/task/Email.java
  src/main/java/profplan/model/task/Task.java
  src/main/java/profplan/model/util/SampleDataUtil.java
  src/main/java/profplan/storage/JsonAdaptedTask.java
  src/main/java/profplan/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/data/JsonProfPlanStorageTest/invalidAndValidTaskProfPlan.json
  src/test/data/JsonProfPlanStorageTest/invalidTaskProfPlan.json
  src/test/data/JsonSerializableProfPlanTest/duplicateTaskProfPlan.json
  src/test/data/JsonSerializableProfPlanTest/invalidTaskProfPlan.json
  src/test/data/JsonSerializableProfPlanTest/typicalTasksProfPlan.json
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/profplan/logic/LogicManagerTest.java
  src/test/java/profplan/logic/commands/CommandTestUtil.java
  src/test/java/profplan/logic/commands/EditTaskDescriptorTest.java
  src/test/java/profplan/logic/parser/AddCommandParserTest.java
  src/test/java/profplan/logic/parser/EditCommandParserTest.java
  src/test/java/profplan/logic/parser/ParserUtilTest.java
  src/test/java/profplan/model/ProfPlanTest.java
  src/test/java/profplan/model/task/AddressTest.java
  src/test/java/profplan/model/task/DueDateTest.java
  src/test/java/profplan/model/task/EmailTest.java
  src/test/java/profplan/model/task/NameContainsKeywordsPredicateTest.java
  src/test/java/profplan/model/task/TaskTest.java
  src/test/java/profplan/model/task/UniqueTaskListTest.java
  src/test/java/profplan/storage/JsonAdaptedTaskTest.java
  src/test/java/profplan/storage/JsonUserPrefsStorageTest.java
  src/test/java/profplan/testutil/EditTaskDescriptorBuilder.java
  src/test/java/profplan/testutil/TaskBuilder.java
  src/test/java/profplan/testutil/TaskUtil.java
  src/test/java/profplan/testutil/TypicalTasks.java
Labels: type.Chore, priority.High

#123 Change printed output for description edits
  src/main/java/profplan/logic/commands/DescriptionCommand.java
Labels: type.Bug, priority.Medium, severity.Medium

#126 Add test cases for the Status class
  src/main/java/profplan/logic/Messages.java
  src/main/java/profplan/model/task/Priority.java
  src/test/java/profplan/model/task/StatusTest.java
Labels: priority.High

#131 Fix bugs
  src/main/java/profplan/logic/parser/ProfPlanParser.java
Labels: type.Bug

#133 Add Urgency-Matrix Functionality
  docs/UserGuide.md
  src/main/java/profplan/model/task/Link.java
  src/main/java/profplan/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Story, type.Epic, type.Enhancement, priority.High

#130 Add recurring tasks
  src/main/java/profplan/logic/commands/DescriptionCommand.java
  src/main/java/profplan/logic/commands/EditCommand.java
  src/main/java/profplan/logic/commands/SetCommand.java
  src/main/java/profplan/logic/parser/AddCommandParser.java
  src/main/java/profplan/logic/parser/CliSyntax.java
  src/main/java/profplan/logic/parser/ParserUtil.java
  src/main/java/profplan/model/task/DueDate.java
  src/main/java/profplan/model/task/Task.java
  src/main/java/profplan/model/util/SampleDataUtil.java
  src/main/java/profplan/storage/JsonAdaptedTask.java
  src/test/java/profplan/storage/JsonAdaptedTaskTest.java
  src/test/java/profplan/testutil/TaskBuilder.java
Labels: type.Story, type.Epic, priority.High
