Repository AY2324S1-CS2103T-W15-1/tp, pull requests merged in 2023-11, with the labels that each got.

#138 Add settings
  .gitignore
  src/main/java/profplan/MainApp.java
  src/main/java/profplan/commons/core/Config.java
  src/main/java/profplan/commons/core/Settings.java
  src/main/java/profplan/logic/commands/EditSettingsCommand.java
  src/main/java/profplan/logic/parser/EditCommandParser.java
  src/main/java/profplan/logic/parser/EditSettingsCommandParser.java
  src/main/java/profplan/logic/parser/ParserUtil.java
  src/main/java/profplan/logic/parser/ProfPlanParser.java
  src/main/java/profplan/model/ModelManager.java
  src/main/java/profplan/model/ReadOnlyUserConfigs.java
  src/main/java/profplan/model/UserConfigs.java
  src/main/java/profplan/model/task/Task.java
  src/main/java/profplan/storage/JsonUserConfigsStorage.java
  src/main/java/profplan/storage/Storage.java
  src/main/java/profplan/storage/StorageManager.java
  src/main/java/profplan/storage/UserConfigsStorage.java
  src/test/java/profplan/logic/LogicManagerTest.java
  src/test/java/profplan/logic/commands/AddCommandIntegrationTest.java
  src/test/java/profplan/logic/commands/ClearCommandTest.java
  src/test/java/profplan/logic/commands/DeleteCommandTest.java
  src/test/java/profplan/logic/commands/EditCommandTest.java
  src/test/java/profplan/logic/commands/FindCommandTest.java
  src/test/java/profplan/logic/commands/ListCommandTest.java
  src/test/java/profplan/model/ModelManagerTest.java
  src/test/java/profplan/storage/StorageManagerTest.java
Labels: type.Epic, priority.High

#144 Fix date bugs in matrix functionality
  src/main/java/profplan/ui/MainWindow.java
Labels: type.Bug, priority.High, severity.High

#146 Fix severe command bugs in do_next and sort
  src/main/java/profplan/logic/parser/ProfPlanParser.java
  src/main/java/profplan/model/ModelManager.java
  src/main/java/profplan/ui/MainWindow.java
Labels: type.Bug, priority.High, severity.High

#148 Fix bugs for sort command
  src/main/java/profplan/logic/commands/SortDueDateCommand.java
  src/main/java/profplan/logic/commands/SortPriorityCommand.java
  src/main/java/profplan/model/ModelManager.java
  src/main/java/profplan/ui/MainWindow.java
Labels: type.Bug, priority.High

#157 Update UG
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/Uif.png
  docs/matrix.png
  docs/team/eyelessrhyme7.md
Labels: priority.High

#152 Fix Bugs for delete all command
  src/main/java/profplan/logic/commands/DeleteCommand.java
Labels: type.Bug

#223 Update DG and finalise PPP
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/UiClassDiagram.png
  docs/images/UmlForModel.png
  docs/team/newway1814.md
Labels: priority.High

#224 Fix priority validation bug
  src/main/java/profplan/model/task/Priority.java
  src/test/java/profplan/testutil/TaskBuilder.java
Labels: type.Bug, priority.High, severity.High

#226 Fix UG URL in Help Window
  src/main/java/profplan/ui/HelpWindow.java
Labels: type.Bug, priority.High, severity.Medium

#227 Fix do_next command returning done tasks bug
  src/main/java/profplan/logic/commands/DoNextCommand.java
  src/main/java/profplan/model/ModelManager.java
Labels: type.Bug, priority.High, severity.High

#228 Fix UrgencyImportance Matrix Bug for displaying furthest tasks
  src/main/java/profplan/ui/MainWindow.java
Labels: type.Bug, priority.High, severity.High

#229 Fix List Command Parsing Bug
  src/main/java/profplan/logic/parser/ProfPlanParser.java
  src/test/java/profplan/logic/parser/ProfPlanParserTest.java
Labels: type.Bug, priority.High, severity.High

#220 Add test cases for Mark and Unmark Command
  src/test/java/profplan/logic/commands/MarkCommandTest.java
  src/test/java/profplan/logic/commands/UnmarkCommandTest.java
  src/test/java/profplan/logic/parser/DeleteCommandParserTest.java
  src/test/java/profplan/logic/parser/MarkCommandParserTest.java
  src/test/java/profplan/logic/parser/UnmarkCommandParserTest.java
Labels: priority.High

#217 Update ug
  docs/UserGuide.md
Labels: type.Bug

#233 Update UG
  docs/UserGuide.md
  docs/images/TeamProfPlan.png
  docs/images/profplan_32.png
  src/main/java/profplan/ui/MainWindow.java
Labels: priority.High, severity.Medium

#218 Fix settings validation
  src/main/java/profplan/commons/core/Settings.java
  src/main/java/profplan/logic/parser/EditSettingsCommandParser.java
  src/main/java/profplan/logic/parser/ParserUtil.java
Labels: type.Bug, priority.Medium, severity.Medium

#232 Edit the sample data
  src/main/java/profplan/model/util/SampleDataUtil.java
Labels: type.Bug, priority.Medium, severity.Low

#250 Miscellaneous changes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/team/kiatkat.md
  src/main/java/profplan/logic/commands/EditSettingsCommand.java
  src/main/java/profplan/logic/parser/EditSettingsCommandParser.java
Labels: type.Chore, type.Bug, priority.Medium, severity.Medium

#254 Update PPP and DG
  docs/DeveloperGuide.md
  docs/team/newway1814.md
Labels: priority.Medium, severity.Low
